"""
The parity harness: prove mobile matches web, instead of asserting it.

    python tools/parity/parity.py                 # owner pass
    python tools/parity/parity.py --role artist
    python tools/parity/parity.py --screens team,clients
    python tools/parity/parity.py --keep-servers   # leave vite/expo up

Output lands in `tools/parity/out/<date>/` with an `index.html` contact
sheet. Nothing is fixed here — the output is a punch list.

─── WHAT IT DOES ───────────────────────────────────────────────────────

1. Boots apps/web (vite) and the apps/mobile web harness against the SAME
   dev database, and signs BOTH in as the SAME account.
2. Per screen: web at 390x844, web at 1440x900, mobile at 390x844.
   Composites web|mobile side by side, and diffs the two mobile-width
   shots where geometry is comparable.
3. Reads computed values off named landmarks on both sides and tabulates
   property | web | mobile | match.
4. Classifies every difference as EXPECTED (named in
   expected-divergences.md) or DRIFT. Drift is the punch list.

─── WHAT IT IS NOT VALID FOR ───────────────────────────────────────────

Layout, type, colour and spacing: valid. MOTION, GESTURES and true native
rendering: NOT VALID, and no output here should be read as covering them.
Reanimated does not advance inside app subtrees under this harness and
gesture-handler is inert to synthetic input — both are recorded in
CLAUDE.md. Those still need the owner's device gate.

─── THE PREVIEW ROUTE ──────────────────────────────────────────────────

The mobile app cannot log in under expo web (secure-store plus CORS), so
a signed-in screen is only reachable by injecting a session. Every
session so far has hand-written a throwaway `preview-XX.tsx`, used it,
and deleted it — which is why this harness exists.

It is still written and removed per run rather than living in
`apps/mobile/src/app` permanently: this is a tool, and a route that ships
in the production bundle to serve it is product code. `_cleanup_stale()`
removes one left behind by a crashed run before starting.
"""

import argparse
import json
import os
import re
import shutil
import signal
import socket
import subprocess
import sys
import time
from datetime import date
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw

sys.path.insert(0, str(Path(__file__).parent))
from manifest import (  # noqa: E402
    DESKTOP_VIEWPORT,
    LANDMARKS,
    MOBILE_VIEWPORT,
    PROPERTIES,
    SCREENS,
    resolve,
)

REPO = Path(__file__).resolve().parents[2]
OUT_ROOT = Path(__file__).parent / "out"
PREVIEW = REPO / "apps" / "mobile" / "src" / "app" / "parity-preview.tsx"

WEB_PORT = 5199
#: apps/web/src/context/auth-context.ts. Not a guess — see the note at
#: the injection site.
WEB_TOKEN_KEY = "ink-manager-token"
EXPO_PORT = 8199
API_PORT = 4000

# ── the injected preview route ─────────────────────────────────────────
# One route, `?screen=` chooses which. Screens that take an id read it
# from these same params, because expo-router gives a screen the params
# of the route that rendered it.
PREVIEW_SOURCE = """import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Text, View } from 'react-native';

import ClientsScreen from '@/app/(tabs)/clients';
/* `(tabs)/index` is the CONVERSATION LIST and `(tabs)/home` is the
   dashboard — the file names, not the tab labels. Checked against the
   router; the first version of this file guessed and failed to bundle. */
import ChatScreen from '@/app/(tabs)/index';
import DashboardScreen from '@/app/(tabs)/home';
import FlashScreen from '@/app/(tabs)/flash';
import InquiriesScreen from '@/app/(tabs)/inquiries';
import ScheduleScreen from '@/app/(tabs)/schedule';
import TeamScreen from '@/app/(tabs)/team';
import ClientDetailScreen from '@/app/client/[id]';
import ConversationScreen from '@/app/conversation/[id]';
import SettingsScreen from '@/app/settings';
import StaffInquiryScreen from '@/app/staff-inquiry/[id]';
import TasksScreen from '@/app/tasks';
import { AuthContext, type AuthContextValue, type Profile, type Studio } from '@/context/auth';
import { apiFetch } from '@/lib/api';

/* GENERATED by tools/parity/parity.py. Written per run and deleted
   afterwards; if you are reading this in a diff, a run crashed. */
const SCREENS: Record<string, () => React.ReactElement> = {
  dashboard: () => <DashboardScreen />,
  inquiries: () => <InquiriesScreen />,
  'staff-inquiry': () => <StaffInquiryScreen />,
  clients: () => <ClientsScreen />,
  client: () => <ClientDetailScreen />,
  chat: () => <ChatScreen />,
  conversation: () => <ConversationScreen />,
  tasks: () => <TasksScreen />,
  schedule: () => <ScheduleScreen />,
  flash: () => <FlashScreen />,
  team: () => <TeamScreen />,
  settings: () => <SettingsScreen />,
};

export default function ParityPreview() {
  const params = useLocalSearchParams<{ screen?: string; token?: string }>();
  const token = params.token ?? '';
  const [profile, setProfile] = useState<Profile | null>(null);
  const [studio, setStudio] = useState<Studio | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    (async () => {
      try {
        const me = await apiFetch<Profile>('/users/me', { token });
        setProfile(me);
        setStudio(await apiFetch<Studio>(`/studios/${me.studioId}`, { token }));
      } catch (err) {
        setError(err instanceof Error ? err.message : String(err));
      }
    })();
  }, [token]);

  if (error) return <Text style={{ color: 'red', padding: 24 }}>{error}</Text>;
  if (!profile) return <View />;

  const auth: AuthContextValue = {
    status: 'signedIn',
    session: { token, profile, studio },
    login: async () => {},
    logout: async () => {},
    applyProfile: () => {},
  };

  const render = SCREENS[params.screen ?? 'dashboard'];
  return (
    <AuthContext value={auth}>
      {render ? render() : <Text style={{ color: 'red', padding: 24 }}>Unknown screen</Text>}
    </AuthContext>
  );
}
"""

# ── landmark probe, run identically on both sides ──────────────────────
# Text-addressed for the reason manifest.py explains. Walks leaf-ish
# elements so a wrapper containing the text does not win over the element
# that actually renders it.
PROBE_JS = """
([text, role, props]) => {
  const wanted = text.trim().toLowerCase();
  const all = [...document.querySelectorAll('*')];
  const hits = all.filter((el) => {
    const own = [...el.childNodes]
      .filter((n) => n.nodeType === 3)
      .map((n) => n.textContent.trim())
      .join(' ')
      .trim()
      .toLowerCase();
    if (own !== wanted) return false;
    if (role && (el.getAttribute('role') || '') !== role) {
      const inner = el.closest(`[role="${role}"]`);
      if (!inner) return false;
    }
    return true;
  });
  if (!hits.length) return null;
  const el = hits[0];
  const cs = getComputedStyle(el);
  const out = {};
  for (const p of props) out[p] = cs[p];
  const r = el.getBoundingClientRect();
  out.__rect = { w: Math.round(r.width), h: Math.round(r.height), x: Math.round(r.x), y: Math.round(r.y) };
  return out;
}
"""


def log(msg):
    print(f"[parity] {msg}", flush=True)


def free(port):
    """
    Is nothing listening on this port — on EITHER stack?

    Checking only 127.0.0.1 is how this harness lost its first two runs.
    A vite orphaned by an earlier attempt was listening on `::1` alone;
    the IPv4 probe reported the port free, the new vite exited
    immediately with "Port 5199 is already in use", and `wait_for` then
    polled a port nothing would ever bind for the full timeout. The error
    it finally raised named the wrong problem entirely.
    """
    for family, host in ((socket.AF_INET, "127.0.0.1"), (socket.AF_INET6, "::1")):
        try:
            with socket.socket(family, socket.SOCK_STREAM) as s:
                s.settimeout(0.4)
                if s.connect_ex((host, port)) == 0:
                    return False
        except OSError:
            continue
    return True


def wait_for(port, what, timeout=180, proc=None):
    """
    Waits for a port, but gives up the moment the process behind it dies.

    Without the `proc` check a server that exits on startup — a port
    clash, a syntax error, a missing env var — costs the full timeout and
    then reports "did not come up", which describes the symptom and hides
    the cause.
    """
    start = time.time()
    while time.time() - start < timeout:
        if not free(port):
            return True
        if proc is not None and proc.poll() is not None:
            raise RuntimeError(
                f"{what} exited during startup (code {proc.returncode}) without binding :{port}. "
                f"Most often the port is already held — check `netstat -ano | findstr :{port}`, "
                f"including IPv6."
            )
        time.sleep(2)
    raise RuntimeError(f"{what} did not come up on :{port} within {timeout}s")


def wait_for_content(page, what, timeout=30):
    """
    Waits until the page has actually rendered something.

    Both a fixed `wait_for_timeout` and a `load` event lie here: web is a
    SPA that paints after hydration, and the mobile harness compiles its
    bundle on the first request. The check is "is there text on screen
    that is not a loading state", which is what a screenshot needs to be
    worth taking.
    """
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            text = page.evaluate("() => document.body.innerText.trim()")
        except Exception:
            text = ""
        if len(text) > 40 and "Loading" not in text[:40]:
            page.wait_for_timeout(700)  # let late images and fonts land
            return True
        page.wait_for_timeout(1000)
    log(f"  ! {what} rendered nothing usable within {timeout}s")
    return False


def _cleanup_stale():
    if PREVIEW.exists():
        log("removing a preview route left by a crashed run")
        PREVIEW.unlink()


def mint_token(role):
    """A dev JWT for the studio the harness runs against."""
    script = Path(__file__).parent / "_token.ts"
    # tsx, from apps/api — see the header of _token.ts for why.
    result = subprocess.run(
        ["npx", "tsx", str(script), role],
        cwd=REPO / "apps" / "api",
        capture_output=True,
        text=True,
        shell=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"token mint failed:\n{result.stdout}\n{result.stderr}")
    data = json.loads(result.stdout.strip().splitlines()[-1])
    return data


def _spawn(command, cwd, env=None):
    """
    Start a dev server and return a handle that can actually kill it.

    TWO WINDOWS-SPECIFIC THINGS, both found by this harness's own first
    run failing:

    1. `shell=True` with a LIST of arguments is unreliable on Windows —
       the list is not joined the way a POSIX shell would, and the run
       silently became a bare `npx` with no arguments, so nothing ever
       bound the port and the wait timed out at 180s with no error. The
       command is a STRING here.

    2. SIGTERM to that shell kills the shell, not the node process it
       started, which leaves an orphan holding the port. The next run
       then finds the port occupied and reuses a server from a previous,
       possibly different, checkout. `CREATE_NEW_PROCESS_GROUP` plus
       taskkill /T in `stop()` kills the tree.
    """
    kwargs = dict(cwd=cwd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if env:
        kwargs["env"] = {**os.environ, **env}
    if os.name == "nt":
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
    return subprocess.Popen(command, **kwargs)


def start_servers(keep):
    procs = []
    if free(API_PORT):
        log(f"starting api on :{API_PORT} (SMS_DRY_RUN, scheduler off)")
        procs.append(_spawn(
            "npx tsx src/index.ts",
            REPO / "apps" / "api",
            {"PORT": str(API_PORT), "SMS_DRY_RUN": "true", "ENABLE_SCHEDULER": "false"},
        ))
        wait_for(API_PORT, "api", proc=procs[-1])
    else:
        log(f"api already up on :{API_PORT}, reusing it")

    if free(WEB_PORT):
        log(f"starting web on :{WEB_PORT}")
        procs.append(_spawn(f"npx vite --port {WEB_PORT} --strictPort", REPO / "apps" / "web"))
        wait_for(WEB_PORT, "web", proc=procs[-1])
    else:
        log(f"web already up on :{WEB_PORT}, reusing it")

    if free(EXPO_PORT):
        log(f"starting the mobile web harness on :{EXPO_PORT}")
        procs.append(_spawn(
            f"npx expo start --web --port {EXPO_PORT}",
            REPO / "apps" / "mobile",
            {"EXPO_PUBLIC_API_URL": f"http://localhost:{API_PORT}"},
        ))
        wait_for(EXPO_PORT, "expo", timeout=420, proc=procs[-1])
    else:
        log(f"expo already up on :{EXPO_PORT}, reusing it")
    return procs


def stop(procs):
    for p in procs:
        try:
            if os.name == "nt":
                # /T for the tree: see _spawn. Without it the node child
                # outlives the shell and keeps the port.
                subprocess.run(["taskkill", "/F", "/T", "/PID", str(p.pid)],
                               capture_output=True, shell=True)
            else:
                p.send_signal(signal.SIGTERM)
        except Exception:
            pass


def composite(web_png, mobile_png, out_png, labels=("web", "mobile")):
    """web | mobile, side by side, labelled."""
    a, b = Image.open(web_png).convert("RGB"), Image.open(mobile_png).convert("RGB")
    gap, header = 24, 28
    h = max(a.height, b.height) + header
    canvas = Image.new("RGB", (a.width + gap + b.width, h), (14, 11, 8))
    canvas.paste(a, (0, header))
    canvas.paste(b, (a.width + gap, header))
    d = ImageDraw.Draw(canvas)
    d.text((4, 8), labels[0].upper(), fill=(201, 154, 91))
    d.text((a.width + gap + 4, 8), labels[1].upper(), fill=(201, 154, 91))
    canvas.save(out_png)
    return out_png


def pixel_diff(web_png, mobile_png, out_png):
    """
    A crude same-size difference map, and it is deliberately crude.

    Two different renderers will never be pixel-identical, so a diff
    IMAGE here is a place to look, never a pass/fail. The returned
    percentage is reported as context and is not a gate — the value
    tables are what actually decide match vs drift.
    """
    a, b = Image.open(web_png).convert("RGB"), Image.open(mobile_png).convert("RGB")
    size = (min(a.width, b.width), min(a.height, b.height))
    a, b = a.crop((0, 0, *size)), b.crop((0, 0, *size))
    diff = ImageChops.difference(a, b).convert("L")
    diff.point(lambda v: 255 if v > 24 else 0).save(out_png)
    hist = diff.histogram()
    changed = sum(hist[25:])
    return round(100.0 * changed / (size[0] * size[1]), 1)


def probe_landmarks(page, screen_key):
    found = {}
    for lm in LANDMARKS:
        if lm.screens and screen_key not in lm.screens:
            continue
        try:
            value = page.evaluate(PROBE_JS, [lm.text, lm.role or "", PROPERTIES])
        except Exception:
            value = None
        found[f"{lm.name} — “{lm.text}”"] = value
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--role", default="owner", choices=["owner", "artist"])
    ap.add_argument("--screens", default="", help="comma-separated keys; default all")
    ap.add_argument("--keep-servers", action="store_true")
    args = ap.parse_args()

    only = {s.strip() for s in args.screens.split(",") if s.strip()}
    screens = [s for s in SCREENS if not only or s.key in only]

    out = OUT_ROOT / date.today().isoformat() / args.role
    shots = out / "shots"
    shots.mkdir(parents=True, exist_ok=True)

    _cleanup_stale()
    PREVIEW.write_text(PREVIEW_SOURCE, encoding="utf-8")
    log(f"wrote {PREVIEW.relative_to(REPO)}")

    procs = []
    results = []
    try:
        session = mint_token(args.role)
        token, ids = session["token"], session["ids"]
        log(f"signed in as {session['email']} ({args.role})")

        procs = start_servers(args.keep_servers)

        from playwright.sync_api import sync_playwright

        with sync_playwright() as pw:
            browser = pw.chromium.launch()

            web = browser.new_page(viewport={"width": MOBILE_VIEWPORT[0], "height": MOBILE_VIEWPORT[1]})
            web.goto(f"http://localhost:{WEB_PORT}/login")
            # 'ink-manager-token', read from apps/web/src/context/auth-context.ts
            # rather than guessed. The first run of this harness used 'token'
            # and every web capture was the login screen — which still looked
            # like a real page, so nothing failed, the landmarks were simply
            # never there.
            web.evaluate(f"(t) => localStorage.setItem({WEB_TOKEN_KEY!r}, t)", token)
            web.goto(f"http://localhost:{WEB_PORT}/dashboard")
            if not wait_for_content(web, "web login"):
                raise RuntimeError(
                    "web never rendered a signed-in page — check WEB_TOKEN_KEY against "
                    "apps/web/src/context/auth-context.ts"
                )

            mobile = browser.new_page(viewport={"width": MOBILE_VIEWPORT[0], "height": MOBILE_VIEWPORT[1]})
            # Playwright's 30s navigation default is not enough for the
            # FIRST request to the mobile harness, which compiles the
            # bundle on demand — the first screen in the list failed every
            # run with "Page.goto: Timeout 30000ms exceeded" while every
            # screen after it passed, which reads as a broken screen
            # rather than a slow compile.
            mobile.set_default_navigation_timeout(180_000)
            mobile.set_default_timeout(180_000)

            # Warm it once, off the clock, so the first real screen is
            # measured under the same conditions as the rest.
            log("warming the mobile bundle")
            try:
                mobile.goto(f"http://localhost:{EXPO_PORT}/parity-preview?screen=team&token={token}")
                wait_for_content(mobile, "mobile warmup", timeout=180)
            except Exception as err:
                log(f"  ! warmup failed: {str(err)[:120]}")

            for s in screens:
                log(f"— {s.title}")
                row = {"key": s.key, "title": s.title, "note": s.note, "web": {}, "mobile": {}}

                if s.web_path is None:
                    row["web_error"] = "no comparable web route (see note)"
                try:
                    if s.web_path is None:
                        raise RuntimeError("skipped")
                    web.set_viewport_size({"width": MOBILE_VIEWPORT[0], "height": MOBILE_VIEWPORT[1]})
                    web.goto(f"http://localhost:{WEB_PORT}{resolve(s.web_path, ids)}")
                    wait_for_content(web, f"web {s.key}")
                    p = shots / f"{s.key}-web-390.png"
                    web.screenshot(path=str(p))
                    row["web_390"] = p.name
                    row["web"] = probe_landmarks(web, s.key)

                    web.set_viewport_size({"width": DESKTOP_VIEWPORT[0], "height": DESKTOP_VIEWPORT[1]})
                    web.wait_for_timeout(1200)
                    p = shots / f"{s.key}-web-1440.png"
                    web.screenshot(path=str(p))
                    row["web_1440"] = p.name
                except Exception as err:
                    if s.web_path is not None:
                        row["web_error"] = str(err)[:200]

                try:
                    params = "&".join(f"{k}={resolve(v, ids)}" for k, v in s.mobile_params.items())
                    url = (
                        f"http://localhost:{EXPO_PORT}/parity-preview"
                        f"?screen={s.mobile_screen}&token={token}"
                        + (f"&{params}" if params else "")
                    )
                    mobile.goto(url)
                    # The FIRST expo web request compiles the bundle and can
                    # take a minute; a fixed sleep produced a pure-white
                    # capture (mean 255, stdev 0) that the run happily
                    # reported as a screen. Waits for real pixels instead.
                    if not wait_for_content(mobile, f"mobile {s.key}", timeout=120):
                        row["mobile_error"] = "rendered nothing within 120s"
                    p = shots / f"{s.key}-mobile-390.png"
                    mobile.screenshot(path=str(p))
                    row["mobile_390"] = p.name
                    row["mobile"] = probe_landmarks(mobile, s.key)
                except Exception as err:
                    row["mobile_error"] = str(err)[:200]

                if row.get("web_390") and row.get("mobile_390"):
                    c = shots / f"{s.key}-composite.png"
                    composite(shots / row["web_390"], shots / row["mobile_390"], c)
                    row["composite"] = c.name
                    d = shots / f"{s.key}-diff.png"
                    row["diff_pct"] = pixel_diff(shots / row["web_390"], shots / row["mobile_390"], d)
                    row["diff"] = d.name

                results.append(row)

            browser.close()
    finally:
        if PREVIEW.exists():
            PREVIEW.unlink()
            log("removed the preview route")
        if not args.keep_servers:
            stop(procs)

    (out / "results.json").write_text(json.dumps(results, indent=2), encoding="utf-8")
    write_index(out, results, args.role)
    log(f"done -> {out / 'index.html'}")


def write_index(out, results, role):
    from report import render_index  # noqa: E402

    (out / "index.html").write_text(render_index(results, role), encoding="utf-8")


if __name__ == "__main__":
    main()
